# NumPy for Numerical Data Analysis

This Colab notebook introduces NumPy arrays and the core operations used to explore and analyse numerical data. Run the cells in order; their example outputs are included below each calculation.

## 1. Setup

In [1]:
import numpy as np

print(f'NumPy version: {np.__version__}')

NumPy version: 2.2.6


## 2. Creating 1D, 2D, and 3D arrays

An array's *axis* represents a dimension. A 1D array is a vector, a 2D array is a table, and a 3D array can represent a stack of tables.

In [2]:
one_d = np.array([10, 20, 30, 40, 50])
two_d = np.array([[1, 2, 3], [4, 5, 6]])
three_d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print('1D array:\n', one_d)
print('\n2D array:\n', two_d)
print('\n3D array:\n', three_d)

1D array:
 [10 20 30 40 50]

2D array:
 [[1 2 3]
 [4 5 6]]

3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## 3. Inspecting dimensions, shape, size, and data type

In [3]:
for name, arr in [('one_d', one_d), ('two_d', two_d), ('three_d', three_d)]:
    print(f'{name}: ndim={arr.ndim}, shape={arr.shape}, size={arr.size}, dtype={arr.dtype}')

one_d: ndim=1, shape=(5,), size=5, dtype=int64
two_d: ndim=2, shape=(2, 3), size=6, dtype=int64
three_d: ndim=3, shape=(2, 2, 2), size=8, dtype=int64


## 4. Indexing and slicing

NumPy uses zero-based indices. In 2D arrays, use `[row, column]`; slices select a range without changing the original array.

In [4]:
scores = np.array([[72, 88, 91], [65, 79, 84], [90, 94, 87]])
print('Scores:\n', scores)
print('\nFirst row:', scores[0])
print('Last value:', scores[-1, -1])
print('First two rows, last two columns:\n', scores[:2, 1:])
print('Every other element in one_d:', one_d[::2])

Scores:
 [[72 88 91]
 [65 79 84]
 [90 94 87]]

First row: [72 88 91]
Last value: 87
First two rows, last two columns:
 [[88 91]
 [79 84]]
Every other element in one_d: [10 30 50]


## 5. Reshaping arrays

`reshape` changes the arrangement of data while preserving the total number of elements.

In [5]:
values = np.arange(1, 13)
matrix = values.reshape(3, 4)
cube = values.reshape(2, 2, 3)

print('Original:', values)
print('\n3 × 4 matrix:\n', matrix)
print('\n2 × 2 × 3 array:\n', cube)

Original: [ 1  2  3  4  5  6  7  8  9 10 11 12]

3 × 4 matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

2 × 2 × 3 array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## 6. Generating arrays with NumPy functions

In [6]:
print('zeros:\n', np.zeros((2, 3)))
print('\nones:\n', np.ones((2, 2), dtype=int))
print('\narange:', np.arange(0, 10, 2))
print('linspace:', np.linspace(0, 1, 5))

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

ones:
 [[1 1]
 [1 1]]

arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]


## 7. Mathematical and vectorized operations

Vectorized operations apply to whole arrays at once—no Python loop is required.

In [7]:
temperatures_c = np.array([18.0, 21.5, 24.0, 19.5, 22.0])
temperatures_f = temperatures_c * 9 / 5 + 32

print('Celsius:', temperatures_c)
print('Fahrenheit:', temperatures_f)
print('Squared:', temperatures_c ** 2)
print('Square roots:', np.sqrt(temperatures_c))
print('Values above 20°C:', temperatures_c - 20)

Celsius: [18.  21.5 24.  19.5 22. ]
Fahrenheit: [64.4 70.7 75.2 67.1 71.6]
Squared: [324.   462.25 576.   380.25 484.  ]
Square roots: [4.24264069 4.63680925 4.89897949 4.41588043 4.69041576]
Values above 20°C: [-2.   1.5  4.  -0.5  2. ]


## 8. Boolean masking

A boolean condition creates a mask that can filter observations meeting a criterion.

In [8]:
sales = np.array([1250, 980, 1430, 760, 1590, 1100])
high_sales = sales >= 1200

print('Sales:', sales)
print('Mask:', high_sales)
print('Sales at least 1200:', sales[high_sales])
print('Count:', high_sales.sum())

Sales: [1250  980 1430  760 1590 1100]
Mask: [ True False  True False  True False]
Sales at least 1200: [1250 1430 1590]
Count: 3


## 9. Broadcasting

Broadcasting lets NumPy combine compatible shapes. Here, a row of department targets is added to every month of results.

In [9]:
monthly_sales = np.array([[100, 120, 90], [110, 115, 105], [130, 125, 110]])
bonus_by_department = np.array([5, 10, 15])
adjusted_sales = monthly_sales + bonus_by_department

print('Monthly sales:\n', monthly_sales)
print('\nBonus:', bonus_by_department)
print('\nBroadcast result:\n', adjusted_sales)

Monthly sales:
 [[100 120  90]
 [110 115 105]
 [130 125 110]]

Bonus: [ 5 10 15]

Broadcast result:
 [[105 130 105]
 [115 125 120]
 [135 135 125]]


## 10. Aggregate functions

Aggregates summarise a dataset. `axis=0` computes a result per column; `axis=1` computes one per row.

In [10]:
data = np.array([[12, 15, 18], [10, 20, 25], [14, 16, 22]])
print('Data:\n', data)
print('\nTotal:', data.sum())
print('Mean:', data.mean())
print('Minimum:', data.min())
print('Maximum:', data.max())
print('Median:', np.median(data))
print('\nColumn means:', data.mean(axis=0))
print('Row sums:', data.sum(axis=1))

Data:
 [[12 15 18]
 [10 20 25]
 [14 16 22]]

Total: 152
Mean: 16.88888888888889
Minimum: 10
Maximum: 25
Median: 16.0

Column means: [12.         17.         21.66666667]
Row sums: [45 55 52]


## Takeaway

NumPy makes numerical analysis concise and fast: arrays store homogeneous data efficiently, vectorization removes explicit loops, and broadcasting plus aggregation make common analysis tasks natural to express.